import React, { Component } from 'react';
import Order from '../../components/Oder/Order'
import axios from '../../axios';
import withErrorHandler from '../../ErrorHandler';


class Orders extends Component {
    state = {
        orders: [],
        loading: true,
    }
    componentDidMount() {
        axios.get('/orders.json').then(res => {
            const fetchedOrders = [];
            for(let key in res.data) {  // key = unique key generated by firebase Db
                fetchedOrders.push({
                    ...res.data[key],
                    id: key
                })
            }
            this.setState({orders: fetchedOrders, loading: false})
        }).catch(err => {
            this.setState({loading: false})
        })
    }
    render() {
        return (
            <div>
               {this.state.orders.map(order => {
                   return <Order 
                   key={order.id} 
                   ingredients={order.ingredients} 
                   price={+order.price}/>
               })}
                
            </div>
        );
    }
}

export default withErrorHandler(Orders, axios);